{% set name = "ilpy" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e56988abe021398ac856ebdc669981028241eb5ecd6427eae315dbf96e2904f7

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler("cxx") }}
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - cython =3.0.9                         # [build_platform != target_platform]
    - setuptools ==71
  host:
    - python {{python}}
    - pip
    - cython =3.0.9
    - scip =9.1.0
    - gurobi =10.0.3  # [linux]
    - gurobi =11.0.3  # [not linux]
  run:
    - python {{python}}
    - scip =9.1.0
    - gurobi =10.0.3  # [linux]
    - gurobi =11.0.3  # [not linux]

test: 
  imports:
    - ilpy
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/funkelab/ilpy
  summary: Unified python wrappers for popular ILP solvers
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tlambert03
    - funkey
